version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: oj_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: ["npm", "run", "build:start"]
    environment:
      - NODE_ENV=production
    depends_on:
      - db
volumes:
  db:
    driver: local
