version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: oj_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: ["npm", "run", "build:start"]
    environment:
      - NODE_ENV=production
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - JWT_SECRET=${JWT_SECRET}
      - APP_PORT=${APP_PORT}
      - JUDGE0_HOST_NAME=${JUDGE0_HOST_NAME}
      - JUDGE0_API_KEY=${JUDGE0_API_KEY}
    depends_on:
      - db
volumes:
  db:
    driver: local
